version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=changeit
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'